// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprkUkaVW5ykH8ED0D_knWRYDrIbA0CCk',
    appId: '1:757921043618:web:86dc00193b1370e028f3fb',
    messagingSenderId: '757921043618',
    projectId: 'flutter-apps-2022',
    authDomain: 'flutter-apps-2022.firebaseapp.com',
    storageBucket: 'flutter-apps-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfwQ8yFdWD7IfttTlXAU-V3I8HyHXrihE',
    appId: '1:757921043618:android:1c292e251d587cbf28f3fb',
    messagingSenderId: '757921043618',
    projectId: 'flutter-apps-2022',
    storageBucket: 'flutter-apps-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7iX3-_fypgbLrsoc9BDi9DJeAsWiUVKM',
    appId: '1:757921043618:ios:f0c64e992e1928b328f3fb',
    messagingSenderId: '757921043618',
    projectId: 'flutter-apps-2022',
    storageBucket: 'flutter-apps-2022.appspot.com',
    iosClientId: '757921043618-68c0mradhbl3gsol6kvj6rgl54rnqism.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrudApp',
  );
}
